services:
  builder:
    build:
      context: ./builder
      dockerfile: Dockerfile.builder
    ports:
      - 3000:3000
    depends_on:
      - mongo
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.node
    environment:
      - PORT = 8000
      - DB_HOST = 127.0.0.1
      - DB_PORT = 27017
      - DB_DATABASE = buidlfy
    ports:
      - 8000:8000
    restart: 'unless-stopped'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
   mongodb: