export const components = [
  {
    name: "Container",
    h: 2,
    style: {
      deleteComponent: 0,
      backgroundColor: { r: "0", g: "0", b: "0" },
      color: { r: "0", g: "0", b: "0", a: "100" },
      borderRadius: 0,
      borderWidth: 0,
      shadow: "none",
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
    children: [],
  },
  {
    name: "Horizontal Container",
    h: 1,
    style: {
      deleteComponent: 0,
      backgroundColor: { r: "0", g: "0", b: "0" },
      color: { r: "0", g: "0", b: "0", a: "100" },
      borderRadius: 1,
      borderWidth: 0,
      shadow: "none",
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
    children: [
      {
        name: "Image",
        h: 4,
        i: 1,
        y: 0,
        x: 0,
        w: 3,
        style: {
          deleteComponent: 0,
          justifyContent: "center",
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
          marginBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
        },
      },
      {
        name: "Text",
        h: 2,
        i: 3,
        y: 0,
        x: 3,
        w: 3,
        value: "Card Paragraph",
        link: "",
        style: {
          color: { r: "0", g: "0", b: "0", a: "100" },
          backgroundColor: { r: "0", g: "0", b: "0" },
          fontWeight: "normal",
          fontStyle: "normal",
          textDecoration: "none",
          justifyContent: "center",
          fontSize: 15,
          deleteComponent: 0,
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
          marginBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
        },
      },
      {
        name: "Heading 1",
        h: 2,
        i: 2,
        y: 0,
        x: 3,
        w: 3,
        value: "Card Title",
        link: "",
        style: {
          color: { r: "0", g: "0", b: "0", a: "100" },
          backgroundColor: { r: "0", g: "0", b: "0" },
          fontWeight: "bold",
          fontStyle: "normal",
          textDecoration: "none",
          justifyContent: "center",
          fontSize: 25,
          deleteComponent: 0,
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
          marginBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
        },
      },
    ],
  },
  {
    name: "Vertical Container",
    h: 1,
    w: 2,
    style: {
      deleteComponent: 0,
      backgroundColor: { r: "0", g: "0", b: "0" },
      color: { r: "0", g: "0", b: "0", a: "100" },
      borderRadius: 1,
      borderWidth: 0,
      shadow: "none",
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },

    children: [
      {
        name: "Image",
        h: 2.2,
        i: 4,
        w: 6,
        x: 0,
        y: 0,
        style: {
          deleteComponent: 0,
          justifyContent: "center",
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
          marginBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
        },
      },
      {
        name: "Heading 1",
        h: 1,
        i: 5,
        w: 6,
        x: 0,
        y: 2,
        value: "Card Title",
        link: "",
        style: {
          color: { r: "0", g: "0", b: "0", a: "100" },
          backgroundColor: { r: "0", g: "0", b: "0" },
          fontWeight: "bold",
          fontStyle: "normal",
          textDecoration: "none",
          justifyContent: "center",
          fontSize: 25,
          deleteComponent: 0,
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
          marginBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
        },
      },
      {
        name: "Text",
        h: 2,
        i: 6,
        w: 6,
        x: 0,
        y: 3,
        value: "Card Paragraph",
        link: "",
        style: {
          color: { r: "0", g: "0", b: "0", a: "100" },
          backgroundColor: { r: "0", g: "0", b: "0" },
          fontWeight: "normal",
          fontStyle: "normal",
          textDecoration: "none",
          justifyContent: "center",
          fontSize: 15,
          deleteComponent: 0,
          marginLeft: 0,
          marginRight: 0,
          marginTop: 0,
          marginBottom: 0,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
        },
      },
    ],
  },
  {
    name: "Button",
    h: 1,
    value: "Add Button",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      backgroundColor: { r: "0", g: "0", b: "0" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 15,
      deleteComponent: 0,
      borderRadius: 0,
      shadow: "none",
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
    connectWallet: "off",
    contract: {},
  },
  {
    name: "Text",
    h: 1,
    value: "Text",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      backgroundColor: { r: "0", g: "0", b: "0" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 15,
      deleteComponent: 0,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
  {
    name: "Heading 1",
    h: 1,
    value: "Heading 1",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      backgroundColor: { r: "0", g: "0", b: "0" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 30,
      deleteComponent: 0,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
  {
    name: "Heading 2",
    h: 1,
    value: "Heading 2",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      backgroundColor: { r: "0", g: "0", b: "0" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 24,
      deleteComponent: 0,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
  {
    name: "Heading 3",
    h: 1,
    value: "Heading 3",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      backgroundColor: { r: "0", g: "0", b: "0" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 18.2,
      deleteComponent: 0,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
  {
    name: "Input",
    h: 1,
    placeholder: "Placeholder",
    style: {
      deleteComponent: 0,
      borderRadius: 0,
      shadow: "none",
      color: { r: "0", g: "0", b: "0", a: "100" },
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
  {
    name: "Image",
    h: 1.2,
    style: {
      deleteComponent: 0,
      justifyContent: "center",
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
  {
    name: "Divider",
    h: 1,
    style: {
      deleteComponent: 0,
      marginLeft: 0,
      marginRight: 0,
      marginTop: 0,
      marginBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
    },
  },
];
