export const fontOptions = [
  { value: `'Inter', sans-serif`, label: `Inter` },
  { value: `'Roboto', sans-serif`, label: `Roboto` },
  { value: `'Audiowide', sans-serif`, label: `Audiowide` },
  { value: `'Open Sans', sans-serif`, label: `Open Sans` },
  { value: `'Montserrat', sans-serif`, label: `Montserrat` },
  { value: `'Lato', sans-serif`, label: `Lato` },
  { value: `'Poppins', sans-serif`, label: `Poppins` },
  { value: `'Roboto Condensed', sans-serif`, label: `Roboto Condensed` },
  { value: `'Oswald', sans-serif`, label: `Oswald` },
  { value: `'Roboto Mono', sans-serif`, label: `Roboto Mono` },
  { value: `'Raleway', sans-serif`, label: `Raleway` },
  { value: `'Noto Sans', sans-serif`, label: `Noto Sans` },
  { value: `'Ubuntu', sans-serif`, label: `Ubuntu` },
  { value: `'Nunito', sans-serif`, label: `Nunito` },
  { value: `'Roboto Slab', serif`, label: `Roboto Slab` },
  { value: `'Playfair Display', serif`, label: `Playfair Display` },
  { value: `'Merriweather', serif`, label: `Merriweather` },
  { value: `'Rubik', sans-serif`, label: `Rubik` },
  { value: `'PT Sans', sans-serif`, label: `PT Sans` },
];
