import { decode as base64_decode } from "base-64";

const BuilderConfig = base64_decode(
  "eyJoZWFkIjp7InRpdGxlIjoiIiwibG9nbyI6IiJ9LCJiYWNrZ3JvdW5kIjp7InIiOiIwIiwiZyI6IjAiLCJiIjoiMCJ9LCJidWlsZGVyIjpbeyJuYW1lIjoiVGV4dCIsImgiOjEsInZhbHVlIjoiVGV4dCIsImxpbmsiOiIiLCJzdHlsZSI6eyJjb2xvciI6eyJyIjoiMCIsImciOiIwIiwiYiI6IjAiLCJhIjoiMTAwIn0sImJhY2tncm91bmRDb2xvciI6eyJyIjoiMCIsImciOiIwIiwiYiI6IjAifSwiZm9udFdlaWdodCI6Im5vcm1hbCIsImZvbnRTdHlsZSI6Im5vcm1hbCIsInRleHREZWNvcmF0aW9uIjoibm9uZSIsImp1c3RpZnlDb250ZW50IjoiY2VudGVyIiwiZm9udFNpemUiOjE1LCJkZWxldGVDb21wb25lbnQiOjB9LCJpIjoiM3NhaDFYIiwieCI6MiwieSI6NSwidyI6MiwibWluVyI6MSwicmVzaXplSGFuZGxlcyI6WyJzZSJdfV0sImNvbnRyYWN0Ijp7ImFiaSI6W10sImFkZHJlc3MiOiIifX0="
);

export default BuilderConfig;
