import { config } from 'dotenv';
config();

export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const {
  NODE_ENV,
  PORT,
  DB_HOST,
  DB_PORT,
  DB_DATABASE,
  BEARER_TOKEN,
  BUIDLFY_TWITTER_ID,
  TWEET_TEXT,
  MAX_RESULTS,
  SECRET_KEY,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  SPHERON_API_HOST,
  DEPLOYMENT_ENDPOINT,
  SPHERON_TOKEN,
  ORGANIZATION_ID,
  DECODER_GIT_URL,
  DECODER_GIT_BRANCH,
  CORS_ADDRESS,
  SITE_DOMAIN_NAME,
  CLOUDFLARE_KEY,
  CLOUDFLARE_EMAIL,
  CDN_CNAME,
  CLOUDFLARE_ZONE_ID,
  WEB3_STORAGE_ACCESS_TOKEN,
} = process.env;
