import { decode as base64_decode } from "base-64";

const BuilderConfig = base64_decode(
  "eyJidWlsZGVyIjpbeyJuYW1lIjoiQnV0dG9uIiwiaCI6MSwidmFsdWUiOiJBZGQgQnV0dG9uIiwibGluayI6IiIsInN0eWxlIjp7ImNvbG9yIjp7InIiOiIwIiwiZyI6IjAiLCJiIjoiMCIsImEiOiIxMDAifSwiYmFja2dyb3VuZENvbG9yIjp7InIiOiIwIiwiZyI6IjAiLCJiIjoiMCJ9LCJmb250V2VpZ2h0Ijoibm9ybWFsIiwiZm9udFN0eWxlIjoibm9ybWFsIiwidGV4dERlY29yYXRpb24iOiJub25lIiwianVzdGlmeUNvbnRlbnQiOiJjZW50ZXIiLCJmb250U2l6ZSI6MTUsImRlbGV0ZUNvbXBvbmVudCI6MCwiYm9yZGVyUmFkaXVzIjoxLCJzaGFkb3ciOiJub25lIn0sImNvbm5lY3RXYWxsZXQiOiJvbiIsImNvbnRyYWN0Ijp7fSwiaSI6IkRpNVMzSiIsIngiOjAsInkiOjIsInciOjYsIm1pblciOjF9XSwiY29udHJhY3QiOnsiYWJpIjpudWxsLCJhZGRyZXNzIjoiIn19"
);

export default BuilderConfig;
