const mintedActionTypes = {
  LIST_TEMPLATE: 'LIST_TEMPLATE',
  FETCH_OWNED_TEMPLATES: 'FETCH_OWNED_TEMPLATES',
  FETCH_OWNED_REVIEW_TEMPLATES: 'FETCH_OWNED_REVIEW_TEMPLATES',
  FETCH_OWNED_LISTED_TEMPLATES: 'FETCH_OWNED_LISTED_TEMPLATES',
};

export default mintedActionTypes;
