const publishActionTypes = {
  INITIATE_PUBLISH: "INITIATE_PUBLISH",
  PUBLISH_DETAILS: "PUBLISH_DETAILS",
  VERIFY_PUBLISH: "VERIFY_PUBLISH",
  UPDATE_PUBLISH: "UPDATE_PUBLISH",
};

export default publishActionTypes;
