import ShortUniqueId from "short-unique-id";

const uid = new ShortUniqueId();
export const components = [
  {
    id: uid(),
    name: "Container",
    h: 1.5,
    style: {
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Button",
    h: 1,
    value: "Add Button",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 15,
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Text",
    h: 1,
    value: "Text",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 15,
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Link",
    h: 1,
    value: "Link",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 15,
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Heading 1",
    h: 2,
    value: "Heading 1",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 32,
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Heading 2",
    h: 2,
    value: "Heading 2",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 24,
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Heading 3",
    h: 2,
    value: "Heading 3",
    link: "",
    style: {
      color: { r: "0", g: "0", b: "0", a: "100" },
      fontWeight: "normal",
      fontStyle: "normal",
      textDecoration: "none",
      justifyContent: "center",
      fontSize: 18.2,
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Input",
    h: 1,
    style: {
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Image",
    h: 3,
    style: {
      deleteComponent: 0,
    },
  },
  {
    id: uid(),
    name: "Divider",
    h: 1,
    style: {
      deleteComponent: 0,
    },
  },
];
